package hackerrank.kangaroo;

import hackerrank.SolutionTester;

import static org.junit.jupiter.api.Assertions.assertTrue;

import org.junit.jupiter.api.Test;

/**
 * https://www.hackerrank.com/challenges/kangaroo
 */
public class TestSolution {
    @Test
    public void testExample0() throws Exception {
        SolutionTester.test(Solution.class, "_example_0");
    }

    @Test
    public void testExample1() throws Exception {
        SolutionTester.test(Solution.class, "_example_1");
    }

    @Test
    public void test00() throws Exception {
        SolutionTester.test(Solution.class, "00");
    }

    @Test
    public void testSame() throws Exception {
        assertTrue(SolutionCore.checkKangaroos(1, 2, 1, 2));
    }

    @Test
    public void test01() throws Exception {
        SolutionTester.test(Solution.class, "01");
    }

    @Test
    public void test02() throws Exception {
        SolutionTester.test(Solution.class, "02");
    }

    @Test
    public void test03() throws Exception {
        SolutionTester.test(Solution.class, "03");
    }

    @Test
    public void test04() throws Exception {
        SolutionTester.test(Solution.class, "05");
    }

    @Test
    public void test05() throws Exception {
        SolutionTester.test(Solution.class, "05");
    }

    @Test
    public void test06() throws Exception {
        SolutionTester.test(Solution.class, "06");
    }

    @Test
    public void test07() throws Exception {
        SolutionTester.test(Solution.class, "07");
    }

    @Test
    public void test08() throws Exception {
        SolutionTester.test(Solution.class, "08");
    }

    @Test
    public void test09() throws Exception {
        SolutionTester.test(Solution.class, "09");
    }

    @Test
    public void test10() throws Exception {
        SolutionTester.test(Solution.class, "10");
    }

    @Test
    public void test11() throws Exception {
        SolutionTester.test(Solution.class, "11");
    }

    @Test
    public void test12() throws Exception {
        SolutionTester.test(Solution.class, "12");
    }

    @Test
    public void test13() throws Exception {
        SolutionTester.test(Solution.class, "13");
    }

    @Test
    public void test14() throws Exception {
        SolutionTester.test(Solution.class, "14");
    }

    @Test
    public void test15() throws Exception {
        SolutionTester.test(Solution.class, "15");
    }

    @Test
    public void test16() throws Exception {
        SolutionTester.test(Solution.class, "16");
    }

    @Test
    public void test17() throws Exception {
        SolutionTester.test(Solution.class, "17");
    }

    @Test
    public void test18() throws Exception {
        SolutionTester.test(Solution.class, "18");
    }

    @Test
    public void test19() throws Exception {
        SolutionTester.test(Solution.class, "19");
    }

    @Test
    public void test20() throws Exception {
        SolutionTester.test(Solution.class, "20");
    }

    @Test
    public void test21() throws Exception {
        SolutionTester.test(Solution.class, "21");
    }

    @Test
    public void test22() throws Exception {
        SolutionTester.test(Solution.class, "22");
    }

    @Test
    public void test23() throws Exception {
        SolutionTester.test(Solution.class, "23");
    }

    @Test
    public void test24() throws Exception {
        SolutionTester.test(Solution.class, "24");
    }

    @Test
    public void test25() throws Exception {
        SolutionTester.test(Solution.class, "25");
    }

    @Test
    public void test26() throws Exception {
        SolutionTester.test(Solution.class, "26");
    }

    @Test
    public void test27() throws Exception {
        SolutionTester.test(Solution.class, "27");
    }

    @Test
    public void test28() throws Exception {
        SolutionTester.test(Solution.class, "28");
    }

    @Test
    public void test29() throws Exception {
        SolutionTester.test(Solution.class, "29");
    }
}
